### ISSUE TITLE
BYO tsconfig issues

### ISSUE THREAD

**Issue by jci-aws** [aws/jsii-compiler#1201]
Hey all - I want to use my own TSConfig file with JSII. Noticed a couple weird things that I'm not sure are intentional or not. Up until now I have been using the generated TSConfig file that JSII creates, here is my config:

`package.json`
```
{
  ...
  "jsii": {
    "outdir": "dist",
    "targets": {},
    "excludeTypescript": [
      ...
    ],
    "tsc": {
      "outDir": "lib",
      "rootDir": "."
    }
  },
  ...
}
```

`tsconfig.json` (generated by JSII)
```
{
  "compilerOptions": {
    "outDir": "lib",
    "rootDir": ".",
    "declarationMap": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "alwaysStrict": true,
    "declaration": true,
    "experimentalDecorators": true,
    "incremental": true,
    "lib": [
      "es2020"
    ],
    "module": "commonjs",
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "stripInternal": false,
    "target": "es2020",
    "composite": false,
    "tsBuildInfoFile": "lib/tsconfig.tsbuildinfo"
  },
  "include": [
    "**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "/path/to/my/project/packages/construct/lib/.types-compat"
    ...
  ],
  "_generated_by_jsii_": "Generated by jsii - safe to delete, and ideally should be in .gitignore"
}
```

### First issue

I saw that JSII >=5.2 allows you to specify your own TSConfig file, so I updated my `package.json` to:
```
{
  ...
  "jsii": {
    "tsconfig": "tsconfig.json",
    "validateTsconfig": "strict"
  },
  ...
}
```
and kept the existing `tsconfig.json` that JSII had been generating. I expected that this would work immediately, since I was thinking that the `tsconfig.json` that JSII generated should be valid, but instead got this error when running `jsii`:
```
error JSII4000: Typescript compiler options in "tsconfig.json" are not passing validation against rule set "strict", found the following rule violations:
  - target: Expected value "es2022", got: "es2020"
  - lib: Expected array matching ["es2022"], got: ["es2020"]
  - esModuleInterop: Expected value true, got: undefined
  - outDir: Unexpected field, got: outDir
```
Is this expected?

### Second issue

I then changed to `"validateTsconfig": "generated"`, and got another error:
```
error JSII4000: Typescript compiler options in "tsconfig.json" are not passing validation against rule set "generated", found the following rule violations:
  - outDir: Unexpected field, got: outDir
```
I looked around the ruleset code and saw [this line](https://github.com/aws/jsii-compiler/blob/b042c57192edb77077e5f2540be997e15362e639/src/tsconfig/rulesets/jsii-configured-options.ts#L7), which I feel may be a typo (should be "outDir" not "outdir") (but also not 100% if that's right since I know the JSII config options in `package.json` take "outdir" (lowercase D) as an option).

Thanks! This is an awesome new feature, very excited to start using it.

**Comment by mrgrain** [comment]
Hey @jci-aws Thanks for the report!

> First issue

Yes, that is expected. The generated jsii file is still tracking settings from much older TS versions. We might consider updating it at some point (not scheduled as of this comment), but wanted to first gather more real-world usage on different settings.

We could maybe try and improve the error message in this scenario. The other question I'd have for you is how we can improve docs. So I guess I am wondering how you noticed this new feature, and if that page (post, whatever) didn't explain correctly how to migrate from a generated config.

> Second issue

Yes, this is a typo. Thanks for the report!

**Comment by mrgrain** [comment]
`ourDir` issue is fixed https://github.com/aws/jsii-compiler/pull/1224

**Comment by jci-aws** [comment]
> We could maybe try and improve the error message in this scenario. The other question I'd have for you is how we can improve docs. So I guess I am wondering how you noticed this new feature, and if that page (post, whatever) didn't explain correctly how to migrate from a generated config.

I was following the official documentation [here](https://aws.github.io/jsii/user-guides/lib-author/configuration/#tsconfig). The error messages were helpful, no issues there.

I did just notice another issue (I can create a separate GH issue for this if you'd like), where if I set `outDir` in my `tsconfig.json` to some value other than `"."`, the `typesVersions` key in `package.json` references the wrong path:

```diff
  "typesVersions": {
    "<=3.9": {
-     "lib/*": [
-       "lib/.types-compat/ts3.9/*",
-       "lib/.types-compat/ts3.9/*/index.d.ts"
+     "*": [
+       ".types-compat/ts3.9/*",
+       ".types-compat/ts3.9/*/index.d.ts"
      ]
    }
  },
```

**Comment by mrgrain** [comment]
Yes please open a separate issue for every issue. 😃

**Comment by jci-aws** [comment]
Opened https://github.com/aws/jsii-compiler/issues/1234 to track. Thanks!
